// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type AkshbpfAkshCfg struct {
	_            structs.HostLayout
	ProxyUid     uint32
	ListenerIp4  uint32
	ListenerPort uint16
	Flags        uint16
	DnsIp4       uint32
	DnsPort      uint16
	Pad          uint16
	Pad2         uint32
	Reserved     uint64
}

type AkshbpfBypassKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      uint32
}

type AkshbpfOrigDst struct {
	_       structs.HostLayout
	Ip      uint32
	Port    uint16
	Flags   uint16
	Uid     uint32
	Pad     uint32
	StampNs uint64
}

type AkshbpfPairKey struct {
	_    structs.HostLayout
	Ip   uint32
	Port uint32
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	AkshbpfMapAkshConfig        = "aksh_config"
	AkshbpfMapBypassCidr4       = "bypass_cidr4"
	AkshbpfMapCookieOrigDst     = "cookie_orig_dst"
	AkshbpfMapPairOrigDst       = "pair_orig_dst"
	AkshbpfProgAkshConnect4     = "aksh_connect4"
	AkshbpfProgAkshConnect6Deny = "aksh_connect6_deny"
	AkshbpfProgAkshSendmsg4     = "aksh_sendmsg4"
	AkshbpfProgAkshSendmsg6     = "aksh_sendmsg6"
	AkshbpfProgAkshSockCreate   = "aksh_sock_create"
	AkshbpfProgAkshSockops      = "aksh_sockops"
)

// LoadAkshbpf returns the embedded CollectionSpec for Akshbpf.
func LoadAkshbpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_AkshbpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Akshbpf: %w", err)
	}

	return spec, err
}

// LoadAkshbpfObjects loads Akshbpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*AkshbpfObjects
//	*AkshbpfPrograms
//	*AkshbpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadAkshbpfObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadAkshbpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// AkshbpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type AkshbpfSpecs struct {
	AkshbpfProgramSpecs
	AkshbpfMapSpecs
	AkshbpfVariableSpecs
}

// AkshbpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type AkshbpfProgramSpecs struct {
	AkshConnect4     *ebpf.ProgramSpec `ebpf:"aksh_connect4"`
	AkshConnect6Deny *ebpf.ProgramSpec `ebpf:"aksh_connect6_deny"`
	AkshSendmsg4     *ebpf.ProgramSpec `ebpf:"aksh_sendmsg4"`
	AkshSendmsg6     *ebpf.ProgramSpec `ebpf:"aksh_sendmsg6"`
	AkshSockCreate   *ebpf.ProgramSpec `ebpf:"aksh_sock_create"`
	AkshSockops      *ebpf.ProgramSpec `ebpf:"aksh_sockops"`
}

// AkshbpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type AkshbpfMapSpecs struct {
	AkshConfig    *ebpf.MapSpec `ebpf:"aksh_config"`
	BypassCidr4   *ebpf.MapSpec `ebpf:"bypass_cidr4"`
	CookieOrigDst *ebpf.MapSpec `ebpf:"cookie_orig_dst"`
	PairOrigDst   *ebpf.MapSpec `ebpf:"pair_orig_dst"`
}

// AkshbpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type AkshbpfVariableSpecs struct {
}

// AkshbpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadAkshbpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type AkshbpfObjects struct {
	AkshbpfPrograms
	AkshbpfMaps
	AkshbpfVariables
}

func (o *AkshbpfObjects) Close() error {
	return _AkshbpfClose(
		&o.AkshbpfPrograms,
		&o.AkshbpfMaps,
	)
}

// AkshbpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadAkshbpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type AkshbpfMaps struct {
	AkshConfig    *ebpf.Map `ebpf:"aksh_config"`
	BypassCidr4   *ebpf.Map `ebpf:"bypass_cidr4"`
	CookieOrigDst *ebpf.Map `ebpf:"cookie_orig_dst"`
	PairOrigDst   *ebpf.Map `ebpf:"pair_orig_dst"`
}

func (m *AkshbpfMaps) Close() error {
	return _AkshbpfClose(
		m.AkshConfig,
		m.BypassCidr4,
		m.CookieOrigDst,
		m.PairOrigDst,
	)
}

// AkshbpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadAkshbpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type AkshbpfVariables struct {
}

// AkshbpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadAkshbpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type AkshbpfPrograms struct {
	AkshConnect4     *ebpf.Program `ebpf:"aksh_connect4"`
	AkshConnect6Deny *ebpf.Program `ebpf:"aksh_connect6_deny"`
	AkshSendmsg4     *ebpf.Program `ebpf:"aksh_sendmsg4"`
	AkshSendmsg6     *ebpf.Program `ebpf:"aksh_sendmsg6"`
	AkshSockCreate   *ebpf.Program `ebpf:"aksh_sock_create"`
	AkshSockops      *ebpf.Program `ebpf:"aksh_sockops"`
}

func (p *AkshbpfPrograms) Close() error {
	return _AkshbpfClose(
		p.AkshConnect4,
		p.AkshConnect6Deny,
		p.AkshSendmsg4,
		p.AkshSendmsg6,
		p.AkshSockCreate,
		p.AkshSockops,
	)
}

func _AkshbpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed akshbpf_bpfel.o
var _AkshbpfBytes []byte
